org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a
newArchEnabled=false
hermesEnabled=true
MYAPP_UPLOAD_STORE_FILE=kidshield-release-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=kidshield
MYAPP_UPLOAD_STORE_PASSWORD=KidShield@2024
MYAPP_UPLOAD_KEY_PASSWORD=KidShield@2024